AllCops:
  NewCops: enable

Layout/LineLength:
  Exclude:
    - 'test/**/*.rb'

Style/MixinUsage:
  Exclude:
    - 'test/**/*.rb'

Style/StringConcatenation:
  Exclude:
    - 'test/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'test/**/*.rb'
